### ISSUE TITLE
Only return preview images

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/page-metadata-parser#17]
On some pages, such as https://cbc.ca the parser will return a tracking image.  We should remove the <img> rule for previewImage.

**Comment by pdehaan** [comment]
Same with www.cnn.com. Currently it's returning 
http://i.cdn.turner.com/ttn/ttn_adspaces/1.0/creatives/2012/2/10/1529111x1.gif

Embed.ly ranks the images by dimensions/complexity, I think.

**Comment by pdehaan** [comment]
Actually, another time, www.cnn.com is giving me this image http://i.cdn.turner.com/cnn/.e1mo/img/4.0/logos/menu_politics.png which I think is a navigation link, not a 1x1 px tracker.

---

![](http://i.cdn.turner.com/cnn/.e1mo/img/4.0/logos/menu_politics.png)
**FIGURE 1:** It looks like a transparent PNG with white text (which renders poorly above).

---

**Comment by jaredkerim** [comment]
We should just only look at the content of preview images and fail to return an image otherwise.
