### ISSUE TITLE
Add Docker file?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/page-metadata-parser#20]
Not sure how we're planning on deploying this, but just a placeholder bug in case we want to have some supported Docker flow for this repo.

Ref: https://github.com/mozilla-services/Dockerflow

**Comment by jaredkerim** [comment]
@pdehaan This repo is meant to store a cross platform (node/browser) library which performs metadata extraction, it does not include exposing a service.  https://github.com/mozilla/page-metadata-service will satisfy that role, which will definitely contain a Docker container and comply with the Mozilla operations dockerflow https://github.com/mozilla-services/Dockerflow
