### ISSUE TITLE
Audit dependencies

### ISSUE THREAD

**Issue by pdehaan** [mozilla/page-metadata-parser#21]
I think most of these are fine, but wasn't sure if we're using **wu**, or if it is safe to remove:

```sh
$ depcheck

Unused Dependencies
* karma-chrome-launcher
* wu

Unused devDependencies
* eslint-plugin-mozilla
* istanbul-instrumenter-loader
* karma-coverage
* karma-firefox-launcher
* karma-mocha
* karma-mocha-reporter
* karma-sourcemap-loader
* karma-webpack
* webpack
```

**Comment by pdehaan** [comment]
Not sure we're currently using **karma-chrome-launcher** either.
I can delete that and **wu** locally and still run `$ npm test`.

**Comment by jaredkerim** [comment]
@pdehaan yeah wu is used by fathom but I think it leaked into my dependency file and can be removed.  And I think your'e right about karma-chrome-launcher as well.

**Comment by pdehaan** [comment]
if you merge #18, I can make a quick PR for this without having a mid-air collision.
