### ISSUE TITLE
Add a command line interface

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/page-metadata-parser#24]
It would be handy if we could invoke the parser to output metadata in json on the command line.

**Comment by pdehaan** [comment]
Would the CLI be in this repo, or in [**page-metadata-service**](https://github.com/mozilla/page-metadata-service)?

**Comment by pdehaan** [comment]
Really bad PR carelessly submitted to https://github.com/mozilla/page-metadata-service/pull/7
