### ISSUE TITLE
Fall back to provided URL if no canonical URL found

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/page-metadata-parser#60]
When we invoke the canonical URL rules, we should pass in the URL in the context, and if the parser is unable to find a URL in the page, return the passed in URL as the canonical URL.

**Comment by pdehaan** [comment]
Interesting fact, Reddit has bogus canonical URLs (for homepage and subreddits, but seemingly not article pages). Filed a bug for it in /r/bugs: https://www.reddit.com/r/bugs/comments/4zr43f/meta_canonical_links_are_bogus/

1. https://www.reddit.com

    ```html
<link rel="canonical" href="https:///" />
```

2. https://www.reddit.com/r/bugs/

    ```html
<link rel="canonical" href="https:///r/bugs/" />
```

3. https://www.reddit.com/r/bugs/comments/4zr43f/meta_canonical_links_are_bogus/

    ```html
<link rel="canonical" href="https://www.reddit.com/r/bugs/comments/4zr43f/meta_canonical_links_are_bogus/" />
```

**Comment by pdehaan** [comment]
Not sure if you want me piggybacking on this issue, or starting a new one, but we may also have to add a `processor` to the canonical URL check to make sure that _THAT_ URL is absolute, because apparently Vimeo isn't:

```html
$ meta-scraper -u  "https://vimeo.com/180763356"

...
<link rel="canonical" href="/180763356">
...
```

**Comment by jaredkerim** [comment]
@pdehaan oh interesting good catch on relative canonical urls!
