### ISSUE TITLE
Add rule set for 'provider' name

### ISSUE THREAD

**Issue by pocmo** [mozilla/page-metadata-parser#79]
Embed.ly returns a provider name:
http://docs.embed.ly/docs/extract

That's something we want to use in the mobile UI of Activity Stream (if available). Also see mozilla/page-metadata-service#90.

Some potential sources are:

Meta tags
- [Open Graph (og:site_name)](http://ogp.me/#optional)
- [application-name](https://www.w3.org/TR/html5/document-metadata.html#standard-metadata-names)
- [twitter:site](https://dev.twitter.com/cards/types/app) (Actually the twitter account, but sometimes a good fallback title)
- [al:android:app_name](http://applinks.org/documentation/)
- [al:ios:app_name](http://applinks.org/documentation/)
- apple-mobile-web-app-title
- [twitter:app:name:iphone](https://dev.twitter.com/cards/types/app)
- [twitter:app:name:ipad](https://dev.twitter.com/cards/types/app)
- [twitter:app:name:googleplay](https://dev.twitter.com/cards/types/app)

Other tags:
- title of <link> tag for RSS/ATOM feeds (Not always the best title or very feed specific)
- title of <link> tag for OpenSearch (Sometimes search specific)

Secondary resources:
- [Web App Manifest (name, short_name)](https://developer.mozilla.org/en-US/docs/Web/Manifest)
- [RSS Feed: channel:title](https://validator.w3.org/feed/docs/rss2.html#requiredChannelElements)
- [ATOM Feed: atom:title](https://tools.ietf.org/html/rfc4287#section-4.2.14)

**Comment by jaredkerim** [comment]
Tagged and published in 0.5.2
