### ISSUE TITLE
Add highres_icon_url rules

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/page-metadata-parser#84]
We need a separate set of rules for just high res icons for callers who want to only know if a high res icon is available for a page.

**Comment by jaredkerim** [comment]
Examples:

    <link rel="apple-touch-icon" href="/apple-touch-icon.png">

    <meta name="msapplication-TileImage" content="/mstile-144x144.png">

**Comment by jaredkerim** [comment]
Our current icon rules appear here for reference, which we wish to decompose into 'application' icons and 'page favicons':

https://github.com/mozilla/page-metadata-parser/blob/master/parser.js#L66-L74
