### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by artemjackson** [mozilla/page-metadata-parser#87]
There are [three input params](https://github.com/mozilla/page-metadata-parser/blob/master/parser.js#L167) in the code but [two in the example](https://github.com/mozilla/page-metadata-parser#using-all-rules). Please update README.md and examples.

**Comment by jaredkerim** [comment]
Fixed in https://github.com/mozilla/page-metadata-parser/commit/fef64a5d1d906328307215891b483451c133d07e
