### ISSUE TITLE
Usage in browser instructions

### ISSUE THREAD

**Issue by pantchox** [mozilla/page-metadata-parser#93]
Hi,
I want to use this lib in the browser but there is only nodejs example.
also the Parser.js file uses node "require" function which is not browser compatiable.

Any advice on this?

thanks

**Comment by jaredkerim** [comment]
@pantchox Hi! You can absolutely use this in the browser, in fact our unit tests include testing it in FIrefox.  You can make a browser deployable version by running:

        npm run clientize

which can be found here: https://github.com/mozilla/page-metadata-parser/blob/master/package.json#L56

This will create a js file that you can drop right into a browser and run directly.

Let me know if this works!  Thanks for trying out the library :)
