### ISSUE TITLE
Icon scoring lacks support for vector icons

### ISSUE THREAD

**Issue by da2x** [mozilla/page-metadata-parser#98]
Size matching in the icon scoring handling only works for bitmap images. Vector images should work just fine but require special handling for the `sizes="any"` property.

    <link href="/icon.svg"
          rel="icon"
          sizes="any"
          type="image/svg">

https://github.com/mozilla/page-metadata-parser/blob/fef64a5d1d906328307215891b483451c133d07e/parser.js#L89-L95

**Comment by Mardak** [comment]
@da2x Firefox 57's implementation of getting rich icons does prefer svg. It was implemented here: https://bugzilla.mozilla.org/show_bug.cgi?id=1352459

On this test page, it just has 2 `<link>`s: https://ed.agadak.net/icon.html
```html
<link rel="icon" href="https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/base/content/abouthome/mozilla.svg" size="any" type="image/svg"/>
<link rel="apple-touch-icon" href="https://www.mozilla.org/media/img/favicon/favicon-196x196.c80e6abe0767.png" sizes="196x196" type="image/png"/>
```

As you can see, Top Sites uses the highest resolution icon available. In this case svg over the "m" 196px png:
<img width="135" alt="image" src="https://user-images.githubusercontent.com/438537/30760304-7870fce4-9f8e-11e7-9afa-da50e5e882aa.png">

Firefox ends up treating "icon" and "apple-touch-icon" both as fallbacks if there are no svg icons. And most pages on the web don't use svg as their "icon". I believe Firefox is already implementing your requested `<link rel="icon" sizes="any" href="/icon.svg"> reign supreme`
